
name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: AutoDeploy Request
         id: deploy
         uses: fjogeleit/http-request-action@master
         with:
           url: 'http://dasd:6643/prod1'
           method: 'POST'
           data: {"ip":"dasd","first_time_commands":"dsadas","commands":"dasdas","repository":"https://github.com/riccihenrique/Zap-Random.git"}
       - name: Show Response
         run: echo ${{ steps.deploy.outputs.response }}
