
name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: AutoDeploy Request
         id: deploy
         uses: fjogeleit/http-request-action@master
         with:
           url: 'http://192.168.0.1:6643/prod1'
           method: 'POST'
           data: "{ "repository": "https://github.com/riccihenrique/Zap-Random.git", "first_time_commands": ["pm2 index.js --name ihaa"], "commands": ["pm2 restart ihaa"] }"
       - name: Show Response
         run: echo ${{ steps.deploy.outputs.response }}
